apiVersion: v1
kind: Pod
metadata:
  name: gateway
spec:
  containers:
  - name: gateway
    image: duarte3108/gatewayfase05
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway
  ports:
  - protocol: TCP
    port: 8085
    targetPort: 80
